version: '3.3'
services:
  api:
    build: .
    command: bash -c "cd /app && rm -f tmp/pids/* && bin/rake db:create && bin/rake db:migrate && bin/rails server -p 3000 -b '0.0.0.0'"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app